// <auto-generated />
using FilmCollector.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FilmFanatic.Migrations
{
    [DbContext(typeof(FilmCollectionContext))]
    partial class FilmCollectionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("FilmCollector.Models.CollectionResponse", b =>
                {
                    b.Property<int>("FilmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("FilmId");

                    b.ToTable("Films");

                    b.HasData(
                        new
                        {
                            FilmId = 1,
                            Category = "Family",
                            Director = "Tom McGrath",
                            Edited = false,
                            Rating = "PG",
                            Title = "Megamind",
                            Year = 2010
                        },
                        new
                        {
                            FilmId = 2,
                            Category = "Family",
                            Director = "Bob Persichetti",
                            Edited = false,
                            Rating = "PG",
                            Title = "Spider-Man: Into the Spider-Verse",
                            Year = 2018
                        },
                        new
                        {
                            FilmId = 3,
                            Category = "Crime",
                            Director = "Mark Gatiss",
                            Edited = false,
                            Rating = "TV-14",
                            Title = "Sherlock",
                            Year = 2018
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
